# Generated by Django 5.2.4 on 2025-07-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_recaudado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_y_hora_cierre', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilidad_porcentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_barras', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('orden_compra', 'Orden de Compra'), ('factura_b', 'Factura B')], default='orden_compra', max_length=20)),
                ('estado', models.CharField(default='completada', max_length=50)),
                ('descuento_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('redondeo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.caja')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.venta')),
            ],
        ),
    ]
