# Generated by Django 5.2.4 on 2025-08-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_ventadetalle_descuento_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cerrada', 'Cerrada')], default='pendiente', max_length=50),
        ),
    ]
